Fasho_Shop/cart/urls.py
from  django.urls  import  path
from  .  import  views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('',views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<int:product_id>/', views.cart_delete, name='cart_delete'),

]

Fasho_Shop/ecomapp/urls.py
from django.urls import path
from .  import views
app_name='ecomapp'
urlpatterns = [
    path('home/', views.allProdCat, name='allProdCat'),

    path('detail/<int:id>/', views.ProDetail, name='ProCatDetail'),
    path('register/', views.register, name='register'),
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('ahome/',views.admin_home, name='admin_home'),
    path('apps/',views.add_pro, name='add_pro'),
    path('delete/<int:pk>/',views.delete_pro,name="delete_pro"),
    path('update/<int:pk>/',views.update_pro,name='update_pro'),
    path('addprod/',views.add_pro,name="add_pro"),
    ]

Fasho_Shop/ecommproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from ecommproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fasho_Shop/cart/models.py
from django.db import models
from ecomapp.models import Product


# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

Fasho_Shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from ecomapp.models import Product
from .models import Cart, CartItem


# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except  Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request))

        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except   CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except  ObjectDoesNotExist:
        pass
    return render(request, "cart.html", dict(cart_items=cart_items, counter=counter, total=total))


def  cart_payment(request, total=0, counter=0, cart_items= None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except  ObjectDoesNotExist:
        pass
    return render(request, "pay.html", dict(counter= counter, total= total, cart_items= cart_items))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def cart_delete(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

Fasho_Shop/templates/add_product.html
<form method ='POST'  enctype="multipart/form-data">
  {%  csrf_token  %}
  {{form.as_p}}
  <button type="submit">add</button>
</form>

Fasho_Shop/templates/admin_view.html
 <html>
 <charset="utf-8">
 <head>
    <title>products</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>

<body>
	<h1>Product Details</h1>
	<table class="table">
	<thead>
		<tr>
			<th>product</th>
     		<th>Name</th>
			<th>Description</th>
<th>Price</th>
<th>EDIT</th>
<th>DELETE</th>

			
		</tr>
	</thead>
	<tbody>
	{% for b in prod %}
	<tr>
	   <td>{% if b.name %}<img src="{{b.image.url}}" alt="" style="width:100px">
		{% else %}
		
		<span class="text-muted">no  </span>
		{% endif %}
		
		</td>
		
		<td>{{b.name}}</td>
		<td>{{b.description}}</td>

		<td>{{b.price}}</td>
		<td><a href="{% url 'ecomapp:update_pro' b.pk %}" class="btn btn-danger">update</a></td>
		<td><a href="{% url 'ecomapp:delete_pro' b.pk %}" class="btn btn-danger">Delete</a></td>


	</tr>
	
	{% endfor %}
	<b>ADD MOVIE<a href="{% url 'ecomapp:add_pro'  %}" class="btn btn-danger">add</a></b>
</body>
	 
</html>

Fasho_Shop/templates/base.html
{%  load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"  href="{%  static  'css/custom.css'  %}">
    <link href="{%  static  'css/bootstrap.min.css'  %}"  rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <meta name = "description"  content ="{%  block metadescription  %}{%  endblock %}" >

    <title>{%  block title  %}{%  endblock  %}</title>

</head>
<body class="d-flex flex-column min-vh-100" style= "background-color:#ffffff;">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100&display=swap" rel="stylesheet">
<div class="container">
    {%  include 'header.html'  %}
    {%  include  'navbar.html'  %}
{%  block content  %}
    {%  endblock  %}
    </div>
{%  include  'footer.html'  %}
<script src="{%  static  'js/popper.min.js'  %}"></script>
<script src="{%  static  'js/bootstrap.min.js'  %}"></script>
</body>
</html>

Fasho_Shop/templates/cart.html
{%  extends  'base.html'  %}
{%  load static  %}
{% block metadescription  %}
        Your  cart is here, Place your order.
{%  endblock  %}
{%  block title  %}
    cart - Myshox fashions &  Co
{%  endblock  %}
<body>
{%  block content  %}
    {%  if not cart_items  %}
<div>
    <div  class="text-center">
        <br>
        <h1  class="text-center   my_title">
            Your cart is empty
        </h1>
        <br>
    </div>
</div>
    {%  else  %}
<div>
      <div  class="text-center">
          <br>
          <h1  class ="text-center   my_title">
              Your cart
          </h1>
          <br>
    </div>
</div>
<div  class="row  mx-auto">
    <div  class="col-12  col-sm-12  col-md-12  col-lg-6  text-center">
            <table  class="table  my_custom_table">
                <thead  class="my_thead">
                <tr>
                    <th colspan = "5">
                        Your Items
                    </th>
                </tr>
                </thead>
                <tbody>
                {%  for cart_item in cart_items   %}
                <tr>
                    <td>
                        <img  src="{{cart_item.product.image.url}}"   alt=""  style="width:100px;height:100px;" class="float-left  grounded  custom_image">
                    </td>
                    <td  class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU:  {{cart_item.product.id}}
                        <br>
                        Price:  $ {{cart_item.product.price}}
                        <br>
                        Qty:  {{cart_item.quantity}}  *  $ {{cart_item}}
                    </td>
                    <td>
                        $ {{cart_item.sub_total}}
                    </td>
                        {%   if  cart_item.quantity  <  cart_item.product.stock  %}
                             <td>
                                <a  href="{%   url  'cart:add_cart'   cart_item.product.id  %}"   class="custom_a"> <i class="fa fa-plus   custom_icon" ></i></a>
                &nbsp;                <a href="{%  url  'cart:cart_remove'    cart_item.product.id   %}" class="custom_a"> <i class="fa fa-minus   custom_icon" ></i></a>
                &nbsp;                 <a href="{%  url  'cart:cart_delete'    cart_item.product.id   %}"  class="custom_icon"> <i class="fa fa-trash    custom_icon" ></i> </a>
                             </td>
                        {%   else   %}
                            <td>
                                &nbsp;<a  href="{%  url  'cart:cart_remove'    cart_item.product.id   %}" class="custom_a"> <i class="fa fa-minus   custom_icon" ></i></a>
                                &nbsp; <a href="{%  url  'cart:cart_delete'    cart_item.product.id   %}" class="custom_icon"> delete<i class="fa fa-trash    custom_icon" ></i></a>
                            </td>
                        {%  endif  %}
                </tr>
                {%  endfor  %}
                </tbody>
            </table>
    </div>

<br>
        <div  class = "col-12  col-sm-12  col-md-12  col-lg-6  text-center">
                <table  class="table  my_custom_table">
                    <thead  class="my_thead">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            Please review your Cart items before proceeding the order.
                        </td>
                    </tr>
                    <tr>
                        <td  class="text-left">
                            Your Total is :  <strong> {{total}} </strong>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <div  class="mx_auto">
                    <a  href="{%  url  'ecomapp:allProdCat'   %}"  class="btn btn-secondary   btn-block  my_custom_table"> Continue Shopping</a>

                </div>
        </div>
    </div>

<br>
<br>
<br>
<br>
<br>
<br>

    {%  endif   %}

</body>
{%   endblock  %}

Fasho_Shop/templates/category.html
{%  extends  'base.html'  %}
{%  load static  %}

{% block metadescription  %}
<!--{%   if category   %}-->
<!--        {{product.description|truncatewords:155}}-->
<!--{% else %}-->
        Welcome to the Myshox world. Explore your Fashions
<!--{%  endif  %}-->
{%  endblock  %}

{%  block title  %}
<!--    {%  if category  %}-->
<!--        {{category.name}}-->
<!--    {%  else  %}-->
<!--        See our new collections and new styles.-->
<!--    {%   endif  %}-->
{%  endblock  %}

{%  block content  %}
    {%  if product  %}
        <div>
            <div  class="row  my-row-class">
                <div  class="mx_auto">
                <p><a  href="{%  url  'ecomapp:allProdCat'  %}">Our Collections</a></p>
                    </div>
            </div>
        </div>
    {%  endif  %}
<!--<div>-->
<!--    {%  if  category  %}-->
<!--            <img class= "my_image"  src="{{category.image.url}}"  alt="{{category.name}}"  style="width:100%;height:500px;">-->
<!--</div>-->
<!--<br>-->
<!--<div>-->
<!--    <h1 class="text-center   my_title">{{category.name}}</h1>-->
<!--    <p class=" text-justify">{{category.description}}</p>-->
<!--</div>-->
<!--    {%  else  %}-->
<!--<div>-->
                <img  class="my_image   my_image_padding" src="{%  static  'img/GXGHXJG.png'  %}"  alt="Our Products"  style="width:100%;height:500px;">
</div>
<br>
<div>
    <h1 class="text-center  my_title">Fash-O Fashion Products</h1>
    <p class="text-justify">"Fashion ecommerce is the selling and buying of fashion and apparel online. The fashion ecommerce industry is a highly competitive space where stores will try various marketing methods to stand out</p>
</div>
<!--    {%  endif  %}-->
<div  class="container">
    <div  class="row  mx_auto">
        {%  for product in  products  %}
        <div  class="my_bottom_margin  col-9  col-sm-12  col-md-12  col-lg-4">
            <div  class="card  text-center"  style="min-width:16rem;">
                <a href="{% url 'ecomapp:ProCatDetail' product.id %}"><img class="card-img-top   my_image"  src="{{product.image.url}}"  style="height:300px;"  alt="{{product.name}}"></a>
                <div  class="card-body"  style="color:maroon;">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {%   endfor  %}
    </div>
    <div class="mx_auto">
        {%   if products.paginator.num_pages  >  1  %}

        <div  class="text-center">
            {%  for pg in products.paginator.page_range   %}
            <a  href="?page={{pg}}"    class="btn btn-light   btn-sm    {%  if products.number == pg  %} active  {%   endif   %}">{{pg}}</a>
            {%   endfor  %}
        </div>
        {%   endif   %}
    </div>
</div>

{%  endblock  %}

Fasho_Shop/templates/delete_pro.html
<form method="POST">
    {%  csrf_token  %}
    <p>are you sure you want to delete this?</p>
    <input type = 'submit'>
</form>

Fasho_Shop/templates/footer.html
<footer class="bottom"style="margin-bottom:50px;">
<div  class="footer fixed-bottom   my_footer">
   <p  class="text-center"> &copy;  Fash-o fashions. All rights reserved</p>
</div>
   </footer>

Fasho_Shop/templates/header.html
{%  load static  %}
<header>
    <center>
        <a  href="{%  url  'ecomapp:allProdCat'  %}">  <img src="{%  static  'img/JOSHDOAGDGSI.png'  %}"  width="100px;"  height="80px">
    </center>
</header>

Fasho_Shop/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->


</head>
<body>
<div class="col-4"></div>
<div class="col-4 border border-primary ms-5 mt-5">
    <b>Admin Login & user login</b>
<form action="" method="post" class="ps-5 pt-5 pb-5 pe-5 ">
    {% csrf_token %}
    <label for="">username:</label>
    <input type="text" name="username"  placeholder="enter your username" class="form-control"><br>

    <label for="">Password:</label>
    <input type="password" name="password" placeholder="enter your password" class="form-control"><br>

    <input type="submit" value="Login" class="btn btn-primary">
    <a class="" href="{%  url 'ecomapp:register'  %}">Register</a>

</form></div>
<div class="col-4"></div>
{%for msg in messages%}
{{msg}}
{%endfor%}
</body>
</html>

Fasho_Shop/templates/navbar.html
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Fash-O</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{%  url  'ecomapp:allProdCat'   %}">Home</a>
        </li>

        <li class="nav-item dropdown  {%  if 'ecomapp' in request.path  %}active{%  endif  %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{%  url  'ecomapp:allProdCat'   %}">All Products</a></li>
            {%  for cate in links  %}
            <li><a class="dropdown-item" href="{{cate.get_url}}">{{cate.name}}</a></li>
            {%  endfor  %}

          </ul>
        </li>
									{%  if user.is_authenticated  %}
									<li>Hello {{user.username}}</li>
<!--									<li><a href="logout">Logout</a></li>-->
									{%  else  %}
<!--									<li class="nav-item">-->
<!--          <a class="nav-link active" aria-current="page" href="register">REGISTER</a>-->
<!--        </li>-->
<!--									<li><a href="login">Login</a></li>-->
									{%  endif  %}

        {%  if   item_count  > 0 %}
        <li class="nav-item">
          <a class="nav-link "   href="{%  url  'cart:cart_detail'     %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {%  endif  %}
      </ul>
      <form class="d-flex" action=""   method="get">
        {%  csrf_token   %}
        <input class="form-control me-2" type="search" placeholder="Search"  name="q"  aria-label="Search">
        <button class="btn btn-outline-success" type="submit"> <i class="fa fa-search"></i> </button>
      </form>
    </div>
  </div>
</nav>

Fasho_Shop/templates/product.html
{%  extends  'base.html'  %}
{%  load static  %}
{% block metadescription  %}
        {{product.description|truncatewords:155}}
{%  endblock  %}
{%  block title  %}
    {%  if category  %}
        {{product.name}}
    {%   endif  %}
{%  endblock  %}

{%  block content  %}
<div  class="row  my_prod_row_class">
    <div   class="mx_auto">
        <p> <a  href="{%  url  'ecomapp:allProdCat'  %}">Home</a>  |  <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>

</div>
<div  class="container">
    <br>
    <div  class="row">
        <div  class="col-12  col-sm-12  col-md-12  col-lg-6  text-center">
            <div  style="min-width:18rem">
                <img  src="{{product.image.url}}"   alt="{{product.name}}" style="width:300px;height:350px;">
            </div>
        </div>

        <div  class="col-12  col-sm-12  col-md-12  col-lg-6">
            <div>
                <h1  class="my_prod_title">{{product.name}}</h1>
                <p>price- ${{product.price}}</p>
                <p  class="my_title"> Product Description</p>
                <p class="text-justify   my_prod_text">{{product.description}}</p>
                {%  if product.stock  <=  0  %}
                    <p class="text-justify    my_prod_text"> <b>Out of stock</b></p>
                {%  else  %}
                    <a class="btn btn-secondary" href="{%  url  'cart:add_cart'   product.id   %}">Add to cart</a>
                {%   endif   %}
            </div>
        </div>
    </div>
</div>
</div>

{%  endblock  %}

Fasho_Shop/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<div class="col-4"></div>
<div class="col-4 border border-primary ms-5 mt-5">
<form action="" method="post" class="ps-5 pt-5 pb-5 pe-5 ">
    {%csrf_token%}
    <label for="">username:</label>
    <input type="text" name="username"  placeholder="enter your username" class="form-control"><br>
    <label for="">First name:</label>
    <input type="text" name="first_name"  placeholder="enter your first_name" class="form-control"><br>
    <label for="">Last name:</label>
    <input type="text" name="last_name"  placeholder="enter your last_name" class="form-control"><br>
    <label for="">E-mail:</label>
    <input type="email" name="email"  placeholder="enter your email address" class="form-control"><br>
    <label for="">Password:</label>
    <input type="password" name="password" placeholder="enter your password" class="form-control"><br>
    <label for="">Confirm password:</label>
    <input type="password" name="password1"  placeholder="re-enter password" class="form-control"><br>
    <input type="submit" value="register" class="btn btn-success">

</form></div>
<div class="col-4"></div>
{%for msg in message%}
{{msg.user}}
{%endfor%}
</body>
</html>

Fasho_Shop/templates/update.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{f.as_p}}
    <button type="submit">confirm</button>
</form>